package com.zuovx.book.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table operator_log
 */
public class OperatorLog {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * Database Column Remarks:
     *   ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   操作内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * Database Column Remarks:
     *   参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     * Database Column Remarks:
     *   方法名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   0否 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.id
     *
     * @return the value of operator_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.id
     *
     * @param id the value for operator_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.created_at
     *
     * @return the value of operator_log.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.created_at
     *
     * @param createdAt the value for operator_log.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.update_at
     *
     * @return the value of operator_log.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.update_at
     *
     * @param updateAt the value for operator_log.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.ip
     *
     * @return the value of operator_log.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.ip
     *
     * @param ip the value for operator_log.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.operator
     *
     * @return the value of operator_log.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.operator
     *
     * @param operator the value for operator_log.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.params
     *
     * @return the value of operator_log.params
     *
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.params
     *
     * @param params the value for operator_log.params
     *
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.method
     *
     * @return the value of operator_log.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.method
     *
     * @param method the value for operator_log.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.user_id
     *
     * @return the value of operator_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.user_id
     *
     * @param userId the value for operator_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.is_deleted
     *
     * @return the value of operator_log.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.is_deleted
     *
     * @param isDeleted the value for operator_log.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}