package com.zuovx.book.dao;

import com.zuovx.book.model.OperatorLog;
import com.zuovx.book.model.OperatorLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface OperatorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    long countByExample(OperatorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int insert(OperatorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int insertSelective(OperatorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    List<OperatorLog> selectByExample(OperatorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    OperatorLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperatorLog record, @Param("example") OperatorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperatorLog record, @Param("example") OperatorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperatorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperatorLog record);
}